import { useState } from 'react';
import { ArrowRight, Check, CheckCircle, Clock, ShieldCheck, Star, Wallet } from '@phosphor-icons/react';
import { AGENTS, agentById, editable, quote, stationsFor } from './domain.mjs';
import { AgentAvatar, AgentMeta, Mark, Modal, ReportContent, ReportDownload } from './components.jsx';

export function DialogRouter({ modal, job, balance, dispatch, setModal, toast, setView, setMobileTab }) {
  const close = () => setModal(null);
  const act = (action, text) => { dispatch(action); close(); if (text) toast(text); };
  if (modal.type === 'candidates') return <CandidateDialog job={job} station={modal.station} onClose={close} select={agent => act({ type: 'SELECT_AGENT', station: modal.station.id, agentId: agent.id }, `已选择 ${agent.name}，报价已同步`)} />;
  if (modal.type === 'scope') return <ScopeDialog job={job} onClose={close} onSave={patch => act({ type: 'EDIT', patch }, '方案已更新')} />;
  if (modal.type === 'confirm') return <ConfirmDialog job={job} balance={balance} onClose={close} onTopup={() => setModal({ type: 'topup' })} onConfirm={() => { act({ type: 'START' }, '演示资金已托管，开始执行'); setMobileTab('chat'); }} />;
  if (modal.type === 'topup') return <TopupDialog onClose={close} onSubmit={amount => act({ type: 'TOPUP', amount }, `演示余额增加 ${amount} USDC`)} />;
  if (modal.type === 'rework') return <ReasonDialog title="申请一轮返工" description="请说明需要修改的内容。原 Agent 将继续处理，不另收成功费。" submitLabel="提交返工请求" onClose={close} onSubmit={reason => act({ type: 'REWORK', reason }, '返工请求已提交')} />;
  if (modal.type === 'dispute') return <ReasonDialog title="发起争议" description="本订单已使用一次返工。请说明仍不符合哪项验收标准，演示托管资金将保持冻结。" submitLabel="创建争议工单" onClose={close} onSubmit={reason => act({ type: 'DISPUTE', reason }, '争议工单已创建')} />;
  if (modal.type === 'station') return <Modal title={`${modal.station.name} · 工位说明`} eyebrow={modal.station.tag} onClose={close}><div className="modal-body"><div className="spec-list">{[['输入', modal.station.input], ['输出', modal.station.output], ['验收标准', modal.station.acceptance]].map(([label, value]) => <div key={label}><strong>{label}</strong><p>{value}</p></div>)}</div><p className="note">各工位按依赖顺序执行；质量审核由平台自营 Agent 独立完成。</p></div><div className="modal-footer"><button className="button primary" onClick={close}>了解了</button></div></Modal>;
  if (modal.type === 'preview') return <Modal wide title="交付物预览" eyebrow={`VERSION ${job.reworks + 1}.0 · MARKDOWN`} onClose={close}><div className="report-preview"><span className="demo-tag">示例交付物</span><ReportContent job={job} /></div><div className="modal-footer"><button className="button secondary" onClick={close}>关闭预览</button><ReportDownload job={job} /></div></Modal>;
  if (modal.type === 'intermediate') return <Modal title="工位交付记录" eyebrow="RUN ARTIFACTS · 演示" onClose={close}><div className="modal-body artifact-list">{stationsFor(job).map((s, i) => <div key={s.id}><span className={i < job.progress ? 'green-text' : 'muted'}>{i < job.progress ? <CheckCircle weight="fill" size={20} /> : <Clock size={20} />}</span><div><h3>{s.name}</h3><p>{i < job.progress ? s.output : '等待工位完成后生成'}</p></div><span className="badge">{i < job.progress ? '已完成' : '待执行'}</span></div>)}</div><div className="modal-footer"><button className="button primary" onClick={close}>返回对话</button></div></Modal>;
  if (modal.type === 'accept') return <Modal title="确认验收这份交付" eyebrow="FINAL REVIEW" onClose={close}><div className="modal-body"><div className="confirmation-icon"><ShieldCheck size={34} /></div><p>确认交付物符合需求后，系统将按工位结算，并退回未使用的储备。</p><div className="receipt-line"><span>将退回演示钱包</span><strong>{job.reworks ? 24 : 36} USDC</strong></div><p className="note">当前为交互演示，无真实付款或链上交易。</p></div><div className="modal-footer"><button className="button secondary" onClick={close}>继续查看</button><button className="button primary" onClick={() => act({ type: 'ACCEPT' }, '验收完成，演示结算已更新')}>确认验收并结算</button></div></Modal>;
  if (modal.type === 'agent') { const a = modal.agent; return <Modal title={a.name} eyebrow={a.author} onClose={close}><div className="modal-body agent-detail"><AgentAvatar agent={a} /><h3>{a.desc}</h3><p>{a.reason}</p><AgentMeta agent={a} expanded /><div className="metric-pair"><div><strong>{a.pass}%</strong><span>近 30 单一次通过率</span></div><div><strong>{(a.tokens / 1000).toFixed(0)}k</strong><span>Token 上限</span></div></div><div className="note">最近反馈：{a.review}</div><p className="micro muted">履历与评价为展示交互用的示例数据。</p></div><div className="modal-footer"><button className="button secondary" onClick={close}>关闭</button>{a.station !== 'qa' && editable(job) && (a.station !== 'matrix' || job.includeMatrix) && <button className="button primary" onClick={() => { act({ type: 'SELECT_AGENT', station: a.station, agentId: a.id }, '已加入当前方案'); setView('workspace'); }}>加入当前方案<ArrowRight size={16} /></button>}</div></Modal>; }
  return <Modal title="从一个想法，到一份交付" eyebrow="WELCOME TO CREWLINE" onClose={close}><div className="modal-body help-body"><Mark /><p>Crewline 把需求拆成可验收的工位，为你推荐专家 Agent，让每一步都有明确的产出。</p><ol><li><b>聊清需求</b><span>输入目标、范围、期限和预算，或使用示例开始。</span></li><li><b>确认团队</b><span>比较 Agent 履历和报价，随时修改方案。</span></li><li><b>托管并执行</b><span>先确认预算，再开始各工位的依赖执行。</span></li><li><b>验收与交付</b><span>查看稿件，验收结算；也支持一次返工与争议。</span></li></ol><div className="note"><b>关于当前演示</b><p>使用本地规则模拟对话及执行，数据保存在当前浏览器。支付、质检、Webhook、钱包连接和链上身份尚未接入真实服务。附件仅保存文件信息。</p></div></div><div className="modal-footer"><button className="button secondary" onClick={() => { dispatch({ type: 'DEMO' }); close(); setView('workspace'); setMobileTab('chat'); }}>打开示例需求</button><button className="button primary" onClick={close}>开始体验<ArrowRight size={16} /></button></div></Modal>;
}

function CandidateDialog({ job, station, select, onClose }) {
  const [sort, setSort] = useState('recommended'); const selected = agentById(job.agents[station.id]);
  const candidates = AGENTS.filter(a => a.station === station.id).sort((a, b) => sort === 'price' ? a.price - b.price : sort === 'pass' ? b.pass - a.pass : sort === 'speed' ? a.speed - b.speed : (a.id === selected.id ? -1 : b.id === selected.id ? 1 : b.pass - a.pass));
  return <Modal wide title={`选择 ${station.name} Agent`} eyebrow={station.tag} onClose={onClose}><div className="candidate-modal-body"><div className="candidate-intro"><ShieldCheck size={18} /><p>比较履历与报价，为当前工位选择更合适的专家。<span>以下履历为演示数据。</span></p></div><div className="tabs candidate-tabs">{[['recommended', '综合排序'], ['price', '价格'], ['pass', '一次通过率'], ['speed', '交付速度']].map(([id, text]) => <button className={sort === id ? 'active' : ''} key={id} onClick={() => setSort(id)}>{text}</button>)}</div><div className="candidate-options">{candidates.map(a => <article className={`candidate-option ${a.id === selected.id ? 'selected' : ''}`} key={a.id}><div className="candidate-main"><AgentAvatar agent={a} /><div><h3>{a.name}{a.id === selected.id && <span className="selected-label">当前选择</span>}</h3><p>{a.desc}</p><span className="micro muted">by {a.author}</span></div><div className="candidate-price"><b>${a.price}</b><span>USDC / 成功交付</span></div></div><div className="candidate-metrics"><div><span>近 30 单一次通过率</span><strong>{a.pass}%</strong></div><div><span>中位交付时间</span><strong>{a.hours}</strong></div><div><span>Token 上限</span><strong>{(a.tokens / 1000).toFixed(0)}k</strong></div><div><span>交付评价</span><strong className="rating"><Star size={12} weight="fill" />{a.rating} <small>({a.reviews})</small></strong></div></div><div className="candidate-bottom"><p><span>最近反馈：</span>{a.review}</p><button className={`button ${a.id === selected.id ? 'soft' : 'primary'}`} disabled={a.id === selected.id} onClick={() => select(a)}>{a.id === selected.id ? <><Check size={15} />已选择</> : <>{a.price - selected.price > 0 ? '+' : ''}{a.price - selected.price} USDC · 选择</>}</button></div></article>)}</div></div><div className="modal-footer"><span className="micro muted">换人后总报价会立即更新，确认托管前不产生费用。</span><button className="button secondary" onClick={onClose}>返回方案</button></div></Modal>;
}

function ScopeDialog({ job, onClose, onSave }) {
  const [form, setForm] = useState({ brief: job.brief, pages: job.pages, days: job.days, budget: job.budget, includeMatrix: job.includeMatrix });
  return <Modal title="调整需求与方案" eyebrow="MAKE IT YOURS" onClose={onClose}><form onSubmit={e => { e.preventDefault(); onSave({ ...form, pages: Number(form.pages), days: Number(form.days), budget: Number(form.budget) }); }}><div className="modal-body form-grid"><label className="span-2">交付目标<textarea required rows={3} value={form.brief} onChange={e => setForm({ ...form, brief: e.target.value })} /></label><label>目标页数<input type="number" required min="1" max="30" value={form.pages} onChange={e => setForm({ ...form, pages: e.target.value })} /></label><label>交付期限 · 天<input type="number" required min="1" max="90" value={form.days} onChange={e => setForm({ ...form, days: e.target.value })} /></label><label className="span-2">预算上限 · USDC<input type="number" required min="1" max="10000" value={form.budget} onChange={e => setForm({ ...form, budget: e.target.value })} /></label><label className="checkbox-label span-2"><input type="checkbox" checked={form.includeMatrix} onChange={e => setForm({ ...form, includeMatrix: e.target.checked })} /><span><b>包含对比分析工位</b><small>移除后，报告撰写将直接使用采集资料。</small></span></label><div className="note span-2">质量审核为必选工位，费用已包含在平台服务费中。</div></div><div className="modal-footer"><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary" type="submit">保存方案<Check size={16} /></button></div></form></Modal>;
}

function ConfirmDialog({ job, balance, onClose, onConfirm, onTopup }) {
  const [agree, setAgree] = useState(false); const q = quote(job); const insufficient = balance < q.total;
  return <Modal title="确认团队并开始执行" eyebrow="YOUR CREW IS READY" onClose={onClose}><div className="modal-body"><div className="confirm-crew">{stationsFor(job).map(s => { const a = agentById(job.agents[s.id]); return <div key={s.id}><CheckCircle size={19} weight="fill" /><AgentAvatar agent={a} small /><strong>{s.name}</strong><span>{a.name}</span><b>{a.price ? `$${a.price}` : '已包含'}</b></div>; })}</div><div className="confirm-price"><div><span>工位成功费</span><span>${q.success}</span></div><div><span>Token 储备</span><span>${q.reserve}</span></div><div><span>平台服务费（含质检）</span><span>${q.platform}</span></div><div className="confirm-total"><strong>托管总额</strong><strong>${q.total} <small>USDC</small></strong></div></div><div className={`balance-note ${insufficient ? 'error-text' : ''}`}><Wallet size={17} /><span>演示钱包余额：{balance.toFixed(2)} USDC</span>{insufficient && <button onClick={onTopup}>模拟入金</button>}</div><label className="checkbox-label"><input type="checkbox" checked={agree} onChange={e => setAgree(e.target.checked)} /><span>我已核对需求、工位分工及验收规则<small>确认后模拟托管资金，验收前不会结算。</small></span></label><div className="note">这是前端交互演示，不会连接钱包或真实扣款。</div></div><div className="modal-footer"><button className="button secondary" onClick={onClose}>返回调整</button><button className="button primary" disabled={!agree || insufficient || q.total > job.budget} onClick={onConfirm}>确认托管并开始执行<ArrowRight size={16} /></button></div></Modal>;
}

function TopupDialog({ onClose, onSubmit }) {
  const [amount, setAmount] = useState(500);
  return <Modal title="添加演示余额" eyebrow="SIMULATED DEPOSIT" onClose={onClose}><form onSubmit={e => { e.preventDefault(); onSubmit(Number(amount)); }}><div className="modal-body"><p>增加当前浏览器的模拟 USDC 余额，用于体验托管和结算。</p><label className="field">金额 · USDC<input required type="number" min="1" max="10000" value={amount} onChange={e => setAmount(e.target.value)} /></label><div className="amount-options">{[100, 500, 1000].map(n => <button key={n} className={`button ${Number(amount) === n ? 'soft' : 'secondary'}`} type="button" onClick={() => setAmount(n)}>{n} USDC</button>)}</div><p className="note">此操作仅更新本地数据，不会请求支付，也不会生成真实交易。</p></div><div className="modal-footer"><button type="button" className="button secondary" onClick={onClose}>取消</button><button type="submit" className="button primary">确认添加演示余额</button></div></form></Modal>;
}

function ReasonDialog({ title, description, submitLabel, onClose, onSubmit }) {
  const [reason, setReason] = useState(''); const [type, setType] = useState('缺少出处');
  return <Modal title={title} eyebrow="REVIEW & FEEDBACK" onClose={onClose}><form onSubmit={e => { e.preventDefault(); if (reason.trim()) onSubmit(`${type}：${reason.trim()}`); }}><div className="modal-body"><p>{description}</p><div className="reason-options">{['缺少出处', '结构不符', '事实存疑', '其他问题'].map(s => <button key={s} type="button" className={`button ${type === s ? 'soft' : 'secondary'}`} onClick={() => setType(s)}>{s}</button>)}</div><label className="field">具体说明<textarea required rows={4} placeholder="例如：请补充新加坡市场的官方数据来源，并标明资料日期。" value={reason} onChange={e => setReason(e.target.value)} /></label></div><div className="modal-footer"><button className="button secondary" type="button" onClick={onClose}>取消</button><button className="button primary" type="submit" disabled={!reason.trim()}>{submitLabel}</button></div></form></Modal>;
}

