import { useState } from 'react';
import { Plus, MagnifyingGlass, ArrowUpRight, ArrowDownLeft, Wallet, Robot, CheckCircle, CaretRight, Bell, PlugsConnected, ArrowRight, Pause, Play } from '@phosphor-icons/react';
import { AGENTS, STATIONS, statusLabels, quote } from './domain.mjs';
import { AgentAvatar, AgentMeta, Empty, PageHeader, Modal, CheckItem, downloadFile } from './components.jsx';

export function Orders({ state, onNew, onOpen }) {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all');
  const filters = [['all', '全部订单'], ['planned', '待确认'], ['running', '进行中'], ['review', '待验收'], ['completed', '已完成']];
  const jobs = state.jobs.filter(j => j.title.includes(query) && (filter === 'all' || j.status === filter || (filter === 'running' && j.status === 'paused')));
  return <div className="page-content"><PageHeader eyebrow="YOUR WORKSPACE" title="我的订单" text="每一个想法，都有一支 Crew 帮你完成。"><button className="button primary" onClick={onNew}><Plus size={17} />新建需求</button></PageHeader>
    <div className="stat-grid">{[['全部订单', state.jobs.length], ['执行中', state.jobs.filter(j => ['running', 'paused'].includes(j.status)).length], ['待验收', state.jobs.filter(j => j.status === 'review').length], ['已完成', state.jobs.filter(j => j.status === 'completed').length]].map(([label, value]) => <div className="stat-card" key={label}><span>{label}</span><strong>{value.toString().padStart(2, '0')}</strong></div>)}</div>
    <div className="section-toolbar"><div className="tabs" aria-label="订单状态">{filters.map(([id, text]) => <button key={id} className={filter === id ? 'active' : ''} onClick={() => setFilter(id)}>{text}</button>)}</div><label className="search-input"><MagnifyingGlass size={17} /><input aria-label="搜索订单" placeholder="搜索订单" value={query} onChange={e => setQuery(e.target.value)} /></label></div>
    <div className="table-wrap"><table className="orders-table"><thead><tr><th>项目名称</th><th>状态</th><th>工位进度</th><th>总报价</th><th>创建日期</th><th /></tr></thead><tbody>{jobs.map(j => <tr key={j.id}><td><button className="order-title" onClick={() => onOpen(j.id)}>{j.title}<span>{j.id === 'job-demo' ? 'CL-20260923 · 示例需求' : `CL-${j.id.slice(0, 8).toUpperCase()}`}</span></button></td><td><span className={`badge ${j.status}`}>{statusLabels[j.status]}</span></td><td>{j.progress} / {j.includeMatrix ? 4 : 3}<div className="tiny-progress"><span style={{ width: `${j.progress / (j.includeMatrix ? 4 : 3) * 100}%` }} /></div></td><td><b>{quote(j).total}</b> <span className="muted micro">USDC</span></td><td>{new Date(j.createdAt).toLocaleDateString('zh-CN')}</td><td><button className="icon-button" aria-label={`打开${j.title}`} onClick={() => onOpen(j.id)}><ArrowUpRight size={18} /></button></td></tr>)}</tbody></table>{!jobs.length && <Empty title="没有匹配的订单" text="试试其他关键词或订单状态。" />}</div>
  </div>;
}

export function Market({ onAgent }) {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all');
  const agents = AGENTS.filter(a => (filter === 'all' || a.station === filter) && `${a.name}${a.desc}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="page-content"><PageHeader eyebrow="EXPERT AGENTS. REAL RESULTS." title="找到适合你的专家" text="按能力、履历和价格，为下一份交付组建团队。" /><div className="market-banner"><span className="banner-icon"><PlugsConnected size={28} /></span><div><h3>专业分工，让每一步都有把握</h3><p>独立工位 · 透明报价 · 按交付验收</p></div><span className="demo-tag">示例 Agent 数据</span></div><div className="section-toolbar"><div className="tabs"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>全部专家</button>{STATIONS.map(s => <button key={s.id} className={filter === s.id ? 'active' : ''} onClick={() => setFilter(s.id)}>{s.name}</button>)}</div><label className="search-input"><MagnifyingGlass size={17} /><input aria-label="搜索 Agent" placeholder="搜索 Agent 或能力" value={query} onChange={e => setQuery(e.target.value)} /></label></div><div className="market-grid">{agents.map(a => <article className="market-card" key={a.id}><div className="market-card-top"><AgentAvatar agent={a} /><span className="badge green">{a.station === 'qa' ? '平台自营' : '可接单'}</span></div><h3>{a.name}</h3><p>{a.desc}</p><span className="tag">{STATIONS.find(s => s.id === a.station).tag}</span><div className="market-performance"><div><strong>{a.pass}%</strong><span>近 30 单一次通过率</span></div><div><strong>{a.reviews}</strong><span>完成订单</span></div></div><AgentMeta agent={a} /><button className="button secondary full" onClick={() => onAgent(a)}>查看详情<ArrowRight size={15} /></button></article>)}</div>{!agents.length && <Empty title="暂未找到匹配的专家" text="尝试更短的关键词或其他工位。" />}</div>;
}

export function WalletPage({ state, onTopup }) {
  const held = state.jobs.reduce((sum, j) => sum + j.escrow, 0);
  return <div className="page-content"><PageHeader eyebrow="WALLET & SETTLEMENTS" title="钱包与结算" text="每笔费用都有去向，每次交付都值得信任。" /><div className="wallet-hero"><Wallet size={30} /><div><span>可用演示余额</span><strong>{state.balance.toLocaleString('en-US', { minimumFractionDigits: 2 })}<small>USDC</small></strong></div><button className="button white" onClick={onTopup}><Plus size={16} />模拟入金</button></div><div className="stat-grid three"><div className="stat-card"><span>托管中的资金</span><strong>{held}<small> USDC</small></strong></div><div className="stat-card"><span>累计退回储备</span><strong>{state.jobs.reduce((s, j) => s + (j.refund || 0), 0)}<small> USDC</small></strong></div><div className="stat-card"><span>结算网络</span><strong className="network-label">Base <span className="badge">演示</span></strong></div></div><div className="section-toolbar"><h2>交易记录</h2><span className="muted micro">仅本浏览器的模拟账本，无真实链上交易</span></div><div className="transaction-list">{state.transactions.map(t => <div className="transaction-row" key={t.id}><span className={`transaction-icon ${t.amount > 0 ? 'positive' : ''}`}>{t.amount > 0 ? <ArrowDownLeft size={22} /> : <ArrowUpRight size={22} />}</span><div><b>{t.type}</b><span>{new Date(t.time).toLocaleString('zh-CN')}</span></div><strong className={t.amount > 0 ? 'green-text' : ''}>{t.amount > 0 ? '+' : ''}{t.amount.toFixed(2)} USDC</strong><button className="text-button" onClick={() => downloadFile(`crewline-receipt-${t.id.slice(0, 8)}.json`, JSON.stringify({ ...t, network: 'simulation', realTransaction: false }, null, 2), 'application/json')}>收据</button></div>)}{!state.transactions.length && <Empty icon={Wallet} title="账本从第一笔托管开始" text="确认方案后，你会在这里看到演示托管与结算记录。" />}</div></div>;
}

export function Notifications({ state, onOpen, onRead }) {
  return <div className="page-content"><PageHeader eyebrow="STAY IN THE LOOP" title="消息" text="把注意力留给结果，进度交给我们。"><button className="button secondary" onClick={onRead}>全部标为已读</button></PageHeader><div className="notification-list">{state.notifications.map(n => <button className={`notification-row ${n.read ? '' : 'unread'}`} key={n.id} onClick={() => { onRead(); onOpen(n.jobId); }}><span className="notification-icon"><CheckCircle size={24} /></span><div><b>{n.title}</b><p>{n.text}</p><span>{new Date(n.time).toLocaleString('zh-CN')}</span></div><CaretRight size={18} /></button>)}{!state.notifications.length && <Empty icon={Bell} title="一切尽在掌握" text="工位完成、交付待验收与结算通知会出现在这里。" />}</div></div>;
}

export function Operators({ state, dispatch, toast }) {
  const [form, setForm] = useState(null); const [tested, setTested] = useState(false); const [error, setError] = useState('');
  function openForm(agent = null) { setForm(agent || { id: crypto.randomUUID(), name: '', station: 'collect', price: 100, tokens: 48000, webhook: '', timeout: 2 }); setTested(false); setError(''); }
  function validate() {
    if (!form.name.trim()) return setError('请填写 Agent 名称。');
    let url; try { url = new URL(form.webhook); } catch { return setError('请填写完整的 HTTPS Webhook 地址。'); }
    if (url.protocol !== 'https:') return setError('Webhook 地址需要以 https:// 开头。');
    if (Number(form.price) <= 0 || Number(form.tokens) < 1000 || Number(form.timeout) <= 0) return setError('请填写有效报价、Token 上限（至少 1000）与超时时间。');
    setError(''); setTested(true);
  }
  return <div className="page-content"><PageHeader eyebrow="OPERATOR CONSOLE" title="我的 Agent" text="让你的专业能力，成为下一支 Crew 的一部分。"><button className="button primary" onClick={() => openForm()}><Plus size={17} />接入 Agent</button></PageHeader><div className="stat-grid three"><div className="stat-card"><span>已接入 Agent</span><strong>{state.operators.length}</strong></div><div className="stat-card"><span>正在接单</span><strong>{state.operators.filter(a => a.online).length}</strong></div><div className="stat-card"><span>已结算收益（演示）</span><strong>0<small> USDC</small></strong></div></div>
    {!state.operators.length ? <div className="operator-onboarding"><Empty icon={Robot} title="把你的 Agent 带到 Crewline" text="配置工位、报价与 Webhook，完成样例校验即可体验上架流程。"><button className="button primary" onClick={() => openForm()}><Plus size={16} />接入第一个 Agent</button></Empty><div className="onboarding-steps">{['填写 Agent Card', '设置工位与报价', '运行样例校验', '确认上架'].map((s, i) => <div key={s}><span>{i + 1}</span>{s}</div>)}</div></div> : <div className="operator-list">{state.operators.map(a => <div className="operator-card" key={a.id}><span className="operator-icon"><Robot size={26} /></span><div><h3>{a.name}</h3><p>{STATIONS.find(s => s.id === a.station)?.tag} · ${a.price} USDC · {Number(a.tokens).toLocaleString()} tokens</p><span className="micro muted">Webhook 配置已保存 · 本地配置校验通过</span></div><span className={`badge ${a.online ? 'green' : ''}`}>{a.online ? '接单中' : '已暂停'}</span><button className="button secondary" onClick={() => dispatch({ type: 'TOGGLE_OPERATOR', id: a.id })}>{a.online ? <Pause size={15} /> : <Play size={15} />}{a.online ? '暂停接单' : '恢复接单'}</button><button className="button secondary" onClick={() => openForm(a)}>编辑</button></div>)}</div>}
    <div className="info-panel"><PlugsConnected size={20} /><div><b>开发者接入预览</b><p>此版本只校验本地配置与样例结构，不请求 Webhook，不创建链上身份，也不实际分发任务。</p></div></div>
    {form && <Modal title="接入你的 Agent" eyebrow="AGENT CARD" onClose={() => setForm(null)}><form onSubmit={e => { e.preventDefault(); if (!tested) return validate(); dispatch({ type: 'SAVE_OPERATOR', agent: { ...form, price: Number(form.price), tokens: Number(form.tokens), validated: true, online: true } }); setForm(null); toast('Agent 已上架到演示控制台'); }}><div className="modal-body form-grid"><label className="span-2">Agent 名称<input required placeholder="例如：Research Companion" value={form.name} onChange={e => { setForm({ ...form, name: e.target.value }); setTested(false); }} /></label><label>工位标签<select value={form.station} onChange={e => { setForm({ ...form, station: e.target.value }); setTested(false); }}>{STATIONS.filter(s => s.id !== 'qa').map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>成功交付费 · USDC<input type="number" min="1" max="10000" value={form.price} onChange={e => { setForm({ ...form, price: e.target.value }); setTested(false); }} required /></label><label className="span-2">Webhook URL<input required type="url" placeholder="https://your-agent.example/run" value={form.webhook} onChange={e => { setForm({ ...form, webhook: e.target.value }); setTested(false); }} /></label><label>Token 上限<input type="number" min="1000" value={form.tokens} onChange={e => { setForm({ ...form, tokens: e.target.value }); setTested(false); }} required /></label><label>超时 · 小时<input type="number" min="1" max="48" value={form.timeout} onChange={e => { setForm({ ...form, timeout: e.target.value }); setTested(false); }} required /></label>{error && <p role="alert" className="error-text span-2">{error}</p>}{tested && <div className="sample-results span-2"><CheckItem>检查 1：Agent 名称与工位配置有效</CheckItem><CheckItem>检查 2：HTTPS Webhook 地址格式有效</CheckItem><CheckItem>检查 3：预算、Token 上限与超时有效</CheckItem><p className="micro muted">本地配置演示校验，未连接实际 Webhook。</p></div>}</div><div className="modal-footer"><button className="button secondary" type="button" onClick={() => setForm(null)}>取消</button><button className="button primary" type="submit">{tested ? '确认上架（演示）' : '运行本地配置校验'}<ArrowRight size={15} /></button></div></form></Modal>}
  </div>;
}

