import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowsClockwise, CaretDown, Check, Clock, CurrencyDollar, FileText, Info, MagnifyingGlass, Paperclip, PaperPlaneRight, Pause, Play, Plus, ShieldCheck, SlidersHorizontal, Timer, UsersThree, X } from '@phosphor-icons/react';
import { DEMO_BRIEF, STATIONS, agentById, editable, quote, stationsFor, statusLabels } from './domain.mjs';
import { AgentAvatar, AgentMeta, Avatar, CheckItem, Deliverable, Empty, Mark } from './components.jsx';

export function Workspace({ job, balance, thinking, send, dispatch, modal, mobileTab, setMobileTab }) {
  return <><div className="mobile-tabs"><button className={mobileTab === 'chat' ? 'active' : ''} onClick={() => setMobileTab('chat')}>需求对话</button><button className={mobileTab === 'crew' ? 'active' : ''} onClick={() => setMobileTab('crew')}>团队与报价{job.status !== 'draft' && <span>{stationsFor(job).length}</span>}</button></div><div className={`workspace mobile-${mobileTab}`}><ChatPanel key={job.id} job={job} thinking={thinking} send={send} dispatch={dispatch} modal={modal} /><div className="crew-area"><TeamPanel job={job} modal={modal} /><SummaryPanel job={job} balance={balance} modal={modal} /></div></div></>;
}
function ChatPanel({ job, thinking, send, dispatch, modal }) {
  const [input, setInput] = useState(''); const fileRef = useRef(null); const scrollRef = useRef(null); const lastCount = useRef(job.messages.length); const canEdit = editable(job);
  useEffect(() => { if (scrollRef.current && (job.messages.length !== lastCount.current || thinking)) scrollRef.current.scrollTop = scrollRef.current.scrollHeight; lastCount.current = job.messages.length; }, [job.messages.length, thinking]);
  function submit(e) { e?.preventDefault(); if (!input.trim() || thinking) return; send(input); setInput(''); }
  return <section className="chat-pane" aria-label="需求对话"><div className="chat-scroll" ref={scrollRef}>
    {!job.messages.length && <div className="welcome"><Mark /><span className="eyebrow">YOUR NEXT GREAT RESULT</span><h2>想完成什么？<br />和你的 Crew 聊聊。</h2><p>描述你的目标，我们来拆解任务，<br />找到专家，把想法变成可交付的结果。</p><div className="prompt-options"><button onClick={() => setInput(DEMO_BRIEF)}><MagnifyingGlass size={18} /><div><strong>竞品研究</strong><span>比较产品、市场与商业模式</span></div><ArrowRight size={15} /></button><button onClick={() => setInput('帮我制作一份 10 页的 AI Agent 行业分析报告，一周内交付，预算 650 USDC。')}><FileText size={18} /><div><strong>行业洞察</strong><span>整理趋势、机会与可靠依据</span></div><ArrowRight size={15} /></button></div></div>}
    {job.messages.length > 0 && <div className="conversation-date">今天 <span>·</span> 你的专属工作空间</div>}
    {job.messages.map(m => <div key={m.id} className={`message ${m.role}`}><div className="message-avatar">{m.role === 'user' ? <Avatar /> : <span className="assistant-avatar"><Mark /></span>}</div><div className="message-main"><div className="message-bubble">{m.text.split('\n').map((t, i) => <p key={i} className={!t ? 'paragraph-space' : undefined}>{t || '\u00a0'}</p>)}</div><time>{m.time}</time></div></div>)}
    {thinking && <div className="message assistant"><span className="assistant-avatar"><Mark /></span><div className="thinking" role="status"><span /><span /><span />正在理解你的需求</div></div>}
    {job.status === 'planned' && !thinking && <div className="inline-plan"><div className="section-heading"><span className="success-icon"><Check size={19} weight="bold" /></span><div><h3>已生成工位方案</h3><p>根据你的需求，我拆解出 {stationsFor(job).length} 个工位，并为每个工位推荐合适的专家。</p></div></div><div className="station-flow">{stationsFor(job).map((s, i) => <div className="flow-item" key={s.id}><button className="flow-card" onClick={() => modal({ type: 'station', station: s })}><span className="flow-title"><span className={`step-number step-${i}`}>{i + 1}</span><strong>{s.name}</strong></span><span className="flow-description">{s.id === 'write' ? `撰写 ${job.pages} 页报告` : s.short}</span><span className="candidate-count">{s.id === 'qa' ? <><ShieldCheck size={12} />平台自营</> : <><UsersThree size={12} />3 个候选</>}</span></button>{i < stationsFor(job).length - 1 && <ArrowRight size={15} className="flow-arrow" />}</div>)}</div><p className="plan-footer">你可以查看每个工位的候选 Agent，或告诉我你的调整需求。</p></div>}
    {['running', 'paused'].includes(job.status) && <div className="execution-card"><div className="section-heading"><span className="success-icon"><Play size={18} weight="fill" /></span><div><h3>{job.status === 'paused' ? '执行已暂停' : job.reworks ? '正在处理返工' : '团队协作进行中'}</h3><p>已完成 {job.progress}/{stationsFor(job).length} 个工位 · 模拟执行</p></div></div><div className="timeline">{stationsFor(job).map((s, i) => <div key={s.id} className={`timeline-row ${i < job.progress ? 'done' : i === job.progress ? 'current' : ''}`}><span className="timeline-node">{i < job.progress ? <Check size={12} weight="bold" /> : <span />}</span><strong>{s.name}</strong><span className={`badge ${i < job.progress ? 'green' : ''}`}>{i < job.progress ? '已完成' : i === job.progress ? (job.status === 'paused' ? '已暂停' : '进行中') : '等待中'}</span><small>{i <= job.progress ? agentById(job.agents[s.id]).hours : '依赖上一步'}</small></div>)}</div><div className="execution-actions"><button className="button secondary" onClick={() => dispatch({ type: 'PAUSE' })}>{job.status === 'paused' ? <Play size={14} /> : <Pause size={14} />}{job.status === 'paused' ? '继续执行' : '暂停执行'}</button><button className="button secondary" onClick={() => modal({ type: 'intermediate' })}>查看中间结果</button></div>{job.status === 'running' && <button className="simulation-next" onClick={() => dispatch({ type: 'TICK' })}>演示：推进下一个工位<ArrowRight size={13} /></button>}</div>}
    {['review', 'completed'].includes(job.status) && <Deliverable job={job} onPreview={() => modal({ type: 'preview' })} onRework={() => modal({ type: 'rework' })} onDispute={() => modal({ type: 'dispute' })} onAccept={() => modal({ type: 'accept' })} />}
    {job.status === 'disputed' && <div className="dispute-card"><ShieldCheck size={26} /><h3>争议工单已创建</h3><p>{job.disputeReason}</p><span className="badge">资金保持托管 · 预计 72h 处理</span><button className="button secondary" onClick={() => modal({ type: 'preview' })}>查看交付物</button></div>}
  </div><div className="composer-area">
    {job.status === 'planned' && <div className="quick-prompts"><button onClick={() => setInput('预算改为 450 USDC')}><CurrencyDollar size={13} />调整预算</button><button onClick={() => setInput('换便宜一点的组合')}><ArrowsClockwise size={13} />更经济的组合</button><button onClick={() => modal({ type: 'scope' })}><SlidersHorizontal size={13} />修改需求</button></div>}
    {job.attachments.length > 0 && <div className="attachments">{job.attachments.map((f, i) => <span key={i}><Paperclip size={12} />{f.name}{canEdit && <button aria-label={`移除${f.name}`} onClick={() => dispatch({ type: 'REMOVE_ATTACHMENT', index: i })}><X size={12} /></button>}</span>)}</div>}
    <form className="composer" onSubmit={submit}><input type="file" ref={fileRef} multiple hidden onChange={e => { const files = Array.from(e.target.files || []).map(f => ({ name: f.name, size: f.size, type: f.type })); dispatch({ type: 'ATTACH', files }); e.target.value = ''; }} /><button className="add-button" type="button" aria-label="添加参考文件" title={canEdit ? '添加参考文件（仅保存文件信息）' : '执行后附件已锁定'} disabled={!canEdit} onClick={() => fileRef.current.click()}><Plus size={21} /></button><textarea aria-label="输入需求或修改意见" placeholder={job.status === 'draft' ? '告诉我，你想完成什么…' : '继续告诉我你的需求，或直接修改上面的方案…'} rows={1} value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing) { e.preventDefault(); submit(); } }} /><button className="attach-button icon-button" type="button" aria-label="上传参考附件" disabled={!canEdit} onClick={() => fileRef.current.click()}><Paperclip size={20} /></button><button className="send-button" type="submit" aria-label="发送需求" disabled={!input.trim() || thinking}><PaperPlaneRight size={19} weight="fill" /></button></form><div className="composer-hint">Enter 发送 · Shift + Enter 换行<span>本地交互演示</span></div>
  </div></section>;
}

function TeamPanel({ job, modal }) {
  const blank = job.status === 'draft'; const locked = !editable(job);
  return <section className={`team-pane ${blank ? 'is-empty' : ''}`} aria-label="推荐的 Agent 团队"><div className="team-heading"><div><h2>{locked ? '你的 Agent 团队' : '推荐的 Agent 团队'}</h2><p>{blank ? '聊清需求后，为你找到合适的专家。' : locked ? '团队已锁定，将按工位依赖顺序完成交付。' : '已为你筛选最匹配的专家 Agent，可以按需调整。'}</p></div>{!blank && !locked && <button className="button secondary small-button" onClick={() => modal({ type: 'scope' })}>调整方案</button>}</div>
    {blank ? <Empty icon={UsersThree} title="你的团队，正在等待一个目标" text="从左侧发送需求，工位与候选专家会出现在这里。" /> : <div className="station-cards">{stationsFor(job).map((s, i) => { const a = agentById(job.agents[s.id]); return <article className="station-card" key={s.id}><div className="station-card-header"><button className="station-label" onClick={() => modal({ type: 'station', station: s })}><span className="step-number">{i + 1}</span><strong>{s.name}</strong><span>{s.tag}</span></button>{s.id === 'qa' ? <span className="platform-tag"><ShieldCheck size={12} />平台自营</span> : locked ? <span className={`badge ${i < job.progress ? 'green' : ''}`}>{i < job.progress ? '已完成' : i === job.progress && job.status === 'running' ? '进行中' : '已锁定'}</span> : <button className="candidate-trigger" aria-label={`查看${s.name}候选`} onClick={() => modal({ type: 'candidates', station: s })}>3 位候选<CaretDown size={11} /></button>}</div><div className="agent-row"><AgentAvatar agent={a} /><div className="agent-identity"><h3>{a.name}</h3><p>{a.desc}</p></div><button className="button secondary small-button agent-action" onClick={() => modal(s.id === 'qa' || locked ? { type: 'agent', agent: a } : { type: 'candidates', station: s })}>{s.id === 'qa' || locked ? '查看详情' : '查看候选'}</button></div><AgentMeta agent={a} /><div className="agent-reliability"><ShieldCheck size={12} /><span>近 30 单一次通过率 <b>{a.pass}%</b></span><span>{(a.tokens / 1000).toFixed(0)}k Token 上限</span></div></article>; })}</div>}
    {!blank && <div className="team-footnote"><ShieldCheck size={14} /><span>质量审核由 Crewline 自营 Agent 独立完成</span></div>}
  </section>;
}

function SummaryPanel({ job, modal }) {
  const q = quote(job); const blank = job.status === 'draft'; const locked = !editable(job); const overBudget = q.total > job.budget;
  return <aside className="summary-pane" aria-label="预估方案"><div className="estimate-card"><h2>{locked ? '订单概览' : '预估方案'}</h2><div className="total-price">{blank ? <span className="pending-price">等待你的需求</span> : <><strong>${q.total.toLocaleString()}</strong><span>USDC</span></>}</div>{!blank && <><div className="price-lines"><div><span>工位成功费</span><b>${q.success}</b></div><div><span>Token 储备</span><b>${q.reserve}</b></div><div><span>平台服务费<button className="inline-info" aria-label="平台服务费说明" onClick={() => modal({ type: 'station', station: STATIONS[3] })}><Info size={13} /></button></span><b>${q.platform}</b></div><div className="included-line">含独立质检 · 策划费已免</div></div><div className={`budget-line ${overBudget && !locked ? 'over-budget' : ''}`}><span>预算上限</span><button disabled={locked} onClick={() => modal({ type: 'scope' })}>${job.budget}{!locked && <SlidersHorizontal size={11} />}</button></div>{overBudget && !locked && <p className="budget-warning" role="alert">超出预算 ${q.total - job.budget}，请调整预算或选择更经济的 Agent。</p>}<div className="plan-facts"><div><Timer size={16} /><span>预计交付时间</span><strong>{Math.min(5, job.days)}–{Math.min(8, job.days)} 天</strong></div><div><ArrowsClockwise size={16} /><span>支持 1 轮返工</span></div><div><ShieldCheck size={16} /><span>验收后按工位结算</span></div></div>{!locked ? <><button className="button primary full confirm-plan" disabled={overBudget} onClick={() => modal({ type: 'confirm' })}>确认此方案<ArrowRight size={16} /></button><p className="estimate-hint">确认后锁定 USDC 托管资金，才会开始执行</p></> : <div className="order-status-card"><span className={`badge ${job.status}`}>{statusLabels[job.status]}</span><p>{job.status === 'completed' ? '演示结算已完成，交付物随时可取。' : job.status === 'disputed' ? '托管冻结，等待平台介入。' : `${job.escrow} USDC 已模拟托管`}</p></div>}</>}{blank && <p className="estimate-hint">确认需求后，将自动计算工位费用与总预算。</p>}</div>
    <div className="why-card"><h3>{locked ? '交付有保障' : '为什么选择这些 Agent？'}</h3><CheckItem>匹配你的需求领域</CheckItem><CheckItem>过往任务一次通过率高</CheckItem><CheckItem>价格与交付速度均衡</CheckItem><CheckItem>已通过平台样例任务测试</CheckItem></div><div className="escrow-note"><ShieldCheck size={21} /><p>为结果付费<br /><span>资金托管，验收后再结算</span></p></div><span className="data-note">报价与履历为演示数据</span>
  </aside>;
}

